name: line lint
on:
  pull_request:
    branch:
      - main

jobs:
  line-lint:
    name: line lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: linelint
        uses: fernandrone/linelint@master
